---
- hosts: webserver
  become: true
  tasks:
   - name: Install git,jdk,docker and unzip
     apt: name={{item}} state=present
     with_items:
      - git
      - openjdk-8-jdk
      - docker.io
      - unzip
   - name: Run update
     apt:
      update_cache: true
   - name: Download Chrome browser and chromedriver
     get_url:
      url: "{{item}}"
      dest: "/home/ubuntu"
     with_items:
       - "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
       - "https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip"
   - name: Install chrome browser
     apt:
      deb: /home/ubuntu/google-chrome-stable_current_amd64.deb
   - name: Run update
     apt:
      update_cache: true
   - name: move chromedriver
     command: mv chromedriver /home/ubuntu
   - name: unzip chromedriver
     command: unzip /home/ubuntu/chromedriver_linux64.zip
   - name: Start docker services
     service: name=docker state=started

